# Generated by Django 4.2.7 on 2023-12-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLibros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(choices=[('Ciencia Ficción y Fantasía', 'Ciencia Ficción y Fantasía'), ('Clásicos', 'Clásicos'), ('Novela', 'Novela'), ('Poesía', 'Poesía'), ('Cuentos', 'Cuentos')], default='Novela', max_length=100),
        ),
    ]
