# Generated by Django 4.2.7 on 2023-12-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLibros', '0002_alter_genero_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=200),
        ),
    ]
